services:
  - type: web
    name: toxic-waste-api
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn prediction:app --host 0.0.0.0 --port 10000
    workingDir: linear_regression_model/summative/API
